name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Run e2e tests
      run: npm run test:e2e

    - name: Build application
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=latest" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/github-workflow:prod-${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/github-workflow:prod-latest
          ${{ secrets.DOCKER_USERNAME }}/github-workflow:${{ steps.version.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Production Server
      env:
        NODE_ENV: production
        APP_NAME: ${{ secrets.PROD_APP_NAME }}
        APP_VERSION: ${{ steps.version.outputs.version }}
        API_URL: ${{ secrets.PROD_API_URL }}
        DEBUG: "false"
        DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        DEPLOYMENT_ID: prod-${{ github.sha }}
      run: |
        echo "Deploying to production environment..."
        echo "Environment: $NODE_ENV"
        echo "Version: $APP_VERSION"
        echo "API URL: $API_URL"
        # Add your deployment commands here (e.g., SSH to server, docker commands, etc.)

    - name: Health Check
      run: |
        echo "Performing health check..."
        # Add health check logic here
        # curl -f http://your-production-domain.com/health || exit 1

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Bug fixes and improvements
        draft: false
        prerelease: false
