name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/github-workflow:dev-${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/github-workflow:dev-latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Development Server
      env:
        NODE_ENV: development
        APP_NAME: ${{ secrets.DEV_APP_NAME }}
        APP_VERSION: ${{ github.sha }}
        API_URL: ${{ secrets.DEV_API_URL }}
        DEBUG: "true"
        DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
        DEPLOYMENT_ID: dev-${{ github.sha }}
      run: |
        echo "Deploying to development environment..."
        echo "Environment: $NODE_ENV"
        echo "Version: $APP_VERSION"
        echo "API URL: $API_URL"
        # Add your deployment commands here (e.g., SSH to server, docker commands, etc.)
        
    - name: Health Check
      run: |
        echo "Performing health check..."
        # Add health check logic here
        # curl -f http://your-dev-server.com/health || exit 1
